// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD8ivvLbMmGbsJNtjLnIrkeYCfF5w7rcg',
    appId: '1:587116319413:web:ae792ef05774a2349964fc',
    messagingSenderId: '587116319413',
    projectId: 'test-6cdba',
    authDomain: 'test-6cdba.firebaseapp.com',
    storageBucket: 'test-6cdba.appspot.com',
    measurementId: 'G-XM89TCZQ6E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXvIzMBdKzUbb68dtjUnJ7yAmmYv53a6A',
    appId: '1:587116319413:android:69fd3ef7555a98cf9964fc',
    messagingSenderId: '587116319413',
    projectId: 'test-6cdba',
    storageBucket: 'test-6cdba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqPv0En_SgMhJU3g1vLF31aL_aeMdXoew',
    appId: '1:587116319413:ios:584756b9e80b199f9964fc',
    messagingSenderId: '587116319413',
    projectId: 'test-6cdba',
    storageBucket: 'test-6cdba.appspot.com',
    iosClientId: '587116319413-urtm9okvkc3a5551tjab57bcjklp2fpo.apps.googleusercontent.com',
    iosBundleId: 'com.example.gooseTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqPv0En_SgMhJU3g1vLF31aL_aeMdXoew',
    appId: '1:587116319413:ios:584756b9e80b199f9964fc',
    messagingSenderId: '587116319413',
    projectId: 'test-6cdba',
    storageBucket: 'test-6cdba.appspot.com',
    iosClientId: '587116319413-urtm9okvkc3a5551tjab57bcjklp2fpo.apps.googleusercontent.com',
    iosBundleId: 'com.example.gooseTask',
  );
}
